version: "1.0"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-k8s:1.0
    env_file:
      - web/.env
    environment:
      - PORT=8020
    ports:
      - "8001:8020"
    command: bash -c "chmod +x /app/migrate.sh && bash /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
    image: postgres
    env_file:
      - web/.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
